### ISSUE TITLE
How to split arguments

### ISSUE THREAD

**Issue by fagiothree** [fagiothree/idems_translation#13]
https://github.com/fagiothree/idems_translation/blob/dd7d9f382be1996893ad2dbef001193fc8bccb35/chatbot/insert/translation_functions.js#L13

https://github.com/fagiothree/idems_translation/blob/dd7d9f382be1996893ad2dbef001193fc8bccb35/chatbot/insert/translation_functions.js#L32

I think arguments can also be separated by commas, e.g.  "word1,word2"

**Comment by edmoss94** [comment]
Understood, have replaced this with the following function which should address this problem

function split_args(args){
    return args.split(/[\s,]+/).filter((i) => i);
}
