### ISSUE TITLE
Bug in fixing localization args

### ISSUE THREAD

**Issue by fagiothree** [fagiothree/idems_translation#15]
https://github.com/fagiothree/idems_translation/blob/d8a173cec1cc2c0f3b0a55b620f9a2bfb0e5f30b/chatbot/insert/check_has_any_word_args.js#L131

The arguments should be in a list:
curr_loc[lang][ArgID[ref]].arguments = [UniqueArguments[ref]]

**Comment by edmoss94** [comment]
Good spot, have made the change
